# Generated by Django 4.2.5 on 2024-06-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='product',
            field=models.CharField(choices=[('product1', 'Product 1'), ('product2', 'Product 2'), ('product3', 'Product 3')], default='product1', max_length=100),
        ),
    ]
